[project]
name = "scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.26.79",
    "google-api-python-client>=2.167.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.1",
    "pycognito>=2022.12.0",
]
